--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 17/10/2022 19:37:21
-- Server version: 10.4.24
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE miniloja2017;

--
-- Drop table `categorias`
--
DROP TABLE IF EXISTS categorias;

--
-- Drop table `clientes`
--
DROP TABLE IF EXISTS clientes;

--
-- Drop table `estados`
--
DROP TABLE IF EXISTS estados;

--
-- Drop table `imagens`
--
DROP TABLE IF EXISTS imagens;

--
-- Drop table `pedidos`
--
DROP TABLE IF EXISTS pedidos;

--
-- Drop table `pedidos_itens`
--
DROP TABLE IF EXISTS pedidos_itens;

--
-- Drop table `produtos`
--
DROP TABLE IF EXISTS produtos;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE miniloja2017;

--
-- Create table `user`
--
CREATE TABLE user (
  user_id int(11) NOT NULL AUTO_INCREMENT,
  user_nome varchar(30) DEFAULT NULL,
  user_email varchar(60) DEFAULT NULL,
  user_pw varchar(40) DEFAULT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `produtos`
--
CREATE TABLE produtos (
  pro_id int(11) NOT NULL AUTO_INCREMENT,
  pro_categoria int(11) DEFAULT NULL,
  pro_nome varchar(100) DEFAULT NULL,
  pro_desc text DEFAULT NULL,
  pro_peso double(9, 3) DEFAULT 0.000,
  pro_valor double(15, 2) DEFAULT 0.00,
  pro_altura int(5) DEFAULT 0,
  pro_largura int(5) DEFAULT 0,
  pro_comprimento int(5) DEFAULT 0,
  pro_img varchar(60) DEFAULT NULL,
  pro_slug varchar(100) DEFAULT NULL,
  pro_estoque int(9) DEFAULT 0,
  pro_modelo varchar(40) DEFAULT NULL,
  pro_ref varchar(20) DEFAULT NULL,
  pro_fabricante int(11) DEFAULT NULL,
  pro_ativo char(3) DEFAULT 'NAO',
  pro_frete_free varchar(3) DEFAULT 'NAO',
  PRIMARY KEY (pro_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `pedidos_itens`
--
CREATE TABLE pedidos_itens (
  item_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  item_produto int(11) DEFAULT NULL,
  item_valor double(9, 2) DEFAULT NULL,
  item_qtd int(6) DEFAULT NULL,
  item_ped_cod varchar(50) DEFAULT NULL,
  PRIMARY KEY (item_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `pedidos`
--
CREATE TABLE pedidos (
  ped_id int(11) NOT NULL AUTO_INCREMENT,
  ped_data date DEFAULT NULL,
  ped_hora time DEFAULT NULL,
  ped_cliente int(11) DEFAULT NULL,
  ped_cod varchar(100) DEFAULT NULL,
  ped_ref varchar(40) DEFAULT NULL,
  ped_pag_status varchar(20) DEFAULT NULL,
  ped_pag_forma varchar(20) DEFAULT NULL,
  ped_pag_tipo varchar(20) DEFAULT NULL,
  ped_pag_codigo varchar(220) DEFAULT NULL,
  ped_frete_valor double(9, 2) DEFAULT NULL,
  ped_frete_tipo varchar(20) DEFAULT NULL,
  PRIMARY KEY (ped_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `imagens`
--
CREATE TABLE imagens (
  img_id int(11) NOT NULL AUTO_INCREMENT,
  img_nome varchar(60) DEFAULT NULL,
  img_pro_id int(11) DEFAULT NULL,
  img_pasta varchar(34) DEFAULT NULL,
  PRIMARY KEY (img_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `estados`
--
CREATE TABLE estados (
  estado_id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  estado_sigla char(2) DEFAULT NULL,
  estado_nome varchar(50) DEFAULT NULL,
  PRIMARY KEY (estado_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 30,
AVG_ROW_LENGTH = 606,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  cli_id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  cli_nome varchar(80) DEFAULT NULL,
  cli_sobrenome varchar(80) DEFAULT NULL,
  cli_endereco varchar(100) DEFAULT NULL,
  cli_numero varchar(20) DEFAULT NULL,
  cli_bairro varchar(80) DEFAULT NULL,
  cli_cidade varchar(150) DEFAULT NULL,
  cli_uf varchar(2) DEFAULT NULL,
  cli_cep varchar(10) DEFAULT NULL,
  cli_cpf varchar(12) DEFAULT NULL,
  cli_rg varchar(20) DEFAULT NULL,
  cli_ddd int(2) DEFAULT NULL,
  cli_fone varchar(10) DEFAULT NULL,
  cli_celular varchar(10) DEFAULT NULL,
  cli_email varchar(60) DEFAULT NULL,
  cli_pass varchar(40) DEFAULT NULL,
  cli_data_nasc date DEFAULT NULL,
  cli_data_cad date DEFAULT NULL,
  cli_hora_cad time DEFAULT NULL,
  PRIMARY KEY (cli_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `categorias`
--
CREATE TABLE categorias (
  cate_id int(11) NOT NULL AUTO_INCREMENT,
  cate_nome varchar(80) DEFAULT NULL,
  cate_slug varchar(80) DEFAULT NULL,
  PRIMARY KEY (cate_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table user
--
-- Table miniloja2017.user does not contain any data (it is empty)

-- 
-- Dumping data for table produtos
--
INSERT INTO produtos VALUES
(1, 1, 'Skol', 'Cerveja Skol', 100.000, 2.38, 100, 100, 100, 'skol.png', NULL, 10, NULL, NULL, NULL, 'SIM', 'NAO'),
(2, 1, 'Cerveja Original', 'Cerveja Original', 100.000, 3.79, 100, 100, 100, 'cerveja_original.png', NULL, 10, NULL, NULL, NULL, 'SIM', 'NAO'),
(3, 1, 'RedBull', 'Redbull', 100.000, 9.00, 100, 100, 100, 'redbull.png', NULL, 10, NULL, NULL, NULL, 'SIM', 'NAO'),
(4, 1, 'Refrigerantes', 'Fanta, Coca Cola, Coca Cola Zero', 100.000, 6.99, 100, 100, 100, 'refrigerantes.png', NULL, 10, NULL, NULL, NULL, 'SIM', 'NAO'),
(5, 1, 'Del Valle', 'Suco Del Valle', 100.000, 4.99, 100, 100, 100, 'delvalle.png', NULL, 10, NULL, NULL, NULL, 'SIM', 'NAO'),
(6, 1, 'Corona Extra', 'Cerveja Corona Extra', 100.000, 7.99, 100, 100, 100, 'corona_extra.png', NULL, 10, NULL, NULL, NULL, 'SIM', 'NAO');

-- 
-- Dumping data for table pedidos_itens
--
-- Table miniloja2017.pedidos_itens does not contain any data (it is empty)

-- 
-- Dumping data for table pedidos
--
-- Table miniloja2017.pedidos does not contain any data (it is empty)

-- 
-- Dumping data for table imagens
--
-- Table miniloja2017.imagens does not contain any data (it is empty)

-- 
-- Dumping data for table estados
--
INSERT INTO estados VALUES
(1, 'AC', 'ACRE'),
(2, 'AL', 'ALAGOAS'),
(3, 'AP', 'AMAPÁ'),
(4, 'AM', 'AMAZONAS'),
(5, 'BA', 'BAHIA'),
(6, 'CE', 'CEARÁ'),
(7, 'DF', 'DISTRITO FEDERAL'),
(8, 'ES', 'ESPÍRITO SANTO'),
(9, 'GO', 'GOIÁS'),
(10, 'MA', 'MARANHÃO'),
(11, 'MT', 'MATO GROSSO'),
(12, 'MS', 'MATO GROSSO DO SUL'),
(13, 'MG', 'MINAS GERAIS'),
(14, 'PA', 'PARÁ'),
(15, 'PB', 'PARAÍBA'),
(16, 'PR', 'PARANÁ'),
(17, 'PE', 'PERNAMBUCO'),
(18, 'PI', 'PIAUÍ'),
(19, 'RJ', 'RIO DE JANEIRO'),
(20, 'RN', 'RIO GRANDE DO NORTE'),
(21, 'RS', 'RIO GRANDE DO SUL'),
(22, 'RO', 'RONDÔNIA'),
(23, 'RR', 'RORAIMA'),
(24, 'SC', 'SANTA CATARINA'),
(25, 'SP', 'SÃO PAULO'),
(26, 'SE', 'SERGIPE'),
(27, 'TO', 'TOCANTINS');

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 'Adriano 11111', 'de Souza', 'Rua logos S 11100', '222', 'JD centro', 'Ibitinga', 'PR', '14940000', '88799195208', '0000111111', 16, '33424466', '992765906', 'cursosadrianosites@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', '1985-09-02', '2016-09-02', '22:11:15'),
(2, 'Fabio', 'de Souza', 'Rua Ernesto pena', '222', 'centro', 'Ibitinga', 'SP', '14940000', '21799713970', '1111111111', 19, '992765906', '992765906', 'cursosadriacxcxnosites@gmail.com', '123456', '1980-09-02', '2016-09-02', '22:10:40'),
(3, 'Paulo', 'de Souza', 'Rua Sena111', '222', 'centro', 'Ibitinga', 'SP', '14940000', '13917299518', '1111111111', 16, '00000000', '111111111', 'cursosadrianocxcsites@gmail.com', 'fb8bfd6ad27c885809a5cce115c97115', '2016-09-07', '2016-09-07', '17:30:02');

-- 
-- Dumping data for table categorias
--
INSERT INTO categorias VALUES
(1, 'Sem categoria', 'sem-categoria'),
(2, 'Papelaria', 'papelaria'),
(3, 'Informática', 'informatica');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;